services:
  api:
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    volumes:
      - ./logs:/app/logs

  redis:
    image: "redis:7-alpine"
    container_name: audio-api-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data_volume:/data

volumes:
  redis_data_volume: